UPDATE PUBLIC.IMPORT_STRATEGIES SET IST_LOCALROOT = '/opt/Drops-Server/tmp/Deploy/Server' where IST_LOCALROOT = 'C:\RK\DROPS\Deploy\Server';
UPDATE PUBLIC.IMPORT_STRATEGIES SET IST_LOCALROOT = '/opt/Drops-Server/tmp/Deploy/Agent' where IST_LOCALROOT = 'C:\RK\DROPS\Deploy\Agent';
UPDATE PUBLIC.IMPORT_STRATEGIES SET IST_LOCALROOT = '/opt/Drops-Server/tmp/Deploy/Webconsole' where IST_LOCALROOT = 'C:\RK\DROPS\Deploy\Webconsole';
UPDATE PUBLIC.IMPORT_STRATEGIES SET IST_LOCALROOT = '/opt/Drops-Server/tmp/Deploy/Update/Database' where IST_LOCALROOT = 'C:\RK\DROPS\Deploy\Update\Database';
UPDATE PUBLIC.IMPORT_STRATEGIES SET IST_LOCALROOT = '/opt/Drops-Server/tmp/Deploy/Update/Processes' where IST_LOCALROOT = 'C:\RK\DROPS\Deploy\Update\Processes';
UPDATE PUBLIC.IMPORT_STRATEGIES SET IST_LOCALROOT = '/opt/Drops-Server/tmp/Deploy/Update/Scripts' where IST_LOCALROOT = 'C:\RK\DROPS\Deploy\Update\Scripts';
UPDATE PUBLIC.IMPORT_STRATEGIES SET IST_LOCALROOT = '/opt/Drops-Server/tmp/Deploy/SqlScript/Dummy' where IST_LOCALROOT = 'C:\RK\DROPS\Deploy\SqlScript\Dummy';
UPDATE PUBLIC.IMPORT_STRATEGIES SET IST_LOCALROOT = '/opt/Drops-Server/tmp/Deploy' where IST_LOCALROOT = 'C:\RK\DROPS\Deploy';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy/Server/' where FSD_DIR = 'C:\RK\DROPS\Deploy\Server\';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy/Agent' where FSD_DIR = 'C:\RK\DROPS\Deploy\Agent\';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy/Webconsole' where FSD_DIR = 'C:\RK\DROPS\Deploy\Webconsole\';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy/Update/Database' where FSD_DIR = 'C:\RK\DROPS\Deploy\Update\Database';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy/Update/Processes' where FSD_DIR = 'C:\RK\DROPS\Deploy\Update\Processes';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy/Update/Scripts' where FSD_DIR = 'C:\RK\DROPS\Deploy\Update\Scripts';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy/Update/Scripts' where FSD_DIR = 'C:\RK\DROPS\Deploy\Update\Scripts';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy/SqlScript\Dummy' where FSD_DIR = 'C:\RK\DROPS\Deploy\SqlScript\Dummy';
UPDATE PUBLIC.STR_FSDIRECTORIES SET FSD_DIR = '/opt/Drops-Server/tmp/Deploy' where FSD_DIR = 'C:\RK\DROPS\Deploy';
DELETE FROM PUBLIC.ARTIFACT_RELEASES;
DELETE FROM PUBLIC.DEPLOYMENTS;
DELETE FROM PUBLIC.IMPORT_LOGS;